### ISSUE TITLE
minimega: panic in queueRemove

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#397]
Panic when running `minitest` without `ovs` running...

```
$ sudo bin/minimega 
minimega, Copyright (2014) Sandia Corporation.
Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
the U.S. Government retains certain rights in this software.
minimega$ 2016/01/11 14:26:23 ERROR ovs.go:114: openvswitch cmd failed: &{/bin/ovs-vsctl [/bin/ovs-vsctl add-br mega_bridge] []  <nil>  ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)
 [] <nil> 0xc820262b60 exit status 1 <nil> true [0xc8204ce1f0 0xc8204ce208 0xc8204ce220] [0xc8204ce1f0 0xc8204ce208 0xc8204ce220] [0xc8204ce200 0xc8204ce218] [0x613e90 0x613e90] 0xc820407d40} ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)

2016/01/11 14:26:23 ERROR kvm.go:469: get bridge: ovsAddBridge: exit status 1: ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)

2016/01/11 14:26:23 WARN vm.go:615: unallocated mac address: 13:37:13:37:00:00
2016/01/11 14:26:23 ERROR ovs.go:114: openvswitch cmd failed: &{/bin/ovs-vsctl [/bin/ovs-vsctl add-br mega_bridge] []  <nil>  ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)
 [] <nil> 0xc8203b1ec0 exit status 1 <nil> true [0xc8204f2140 0xc8204f2158 0xc8204f2170] [0xc8204f2140 0xc8204f2158 0xc8204f2170] [0xc8204f2150 0xc8204f2168] [0x613e90 0x613e90] 0xc8200a30e0} ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)

2016/01/11 14:26:23 ERROR kvm.go:469: get bridge: ovsAddBridge: exit status 1: ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)

2016/01/11 14:26:23 ERROR ovs.go:114: openvswitch cmd failed: &{/bin/ovs-vsctl [/bin/ovs-vsctl add-br test_bridge] []  <nil>  ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)
 [] <nil> 0xc820545960 exit status 1 <nil> true [0xc8204b6238 0xc8204b6250 0xc8204b6268] [0xc8204b6238 0xc8204b6250 0xc8204b6268] [0xc8204b6248 0xc8204b6260] [0x613e90 0x613e90] 0xc8202d7080} ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)

2016/01/11 14:26:23 ERROR kvm.go:469: get bridge: ovsAddBridge: exit status 1: ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)

2016/01/11 14:26:23 WARN vm.go:615: unallocated mac address: 13:37:13:37:00:01
2016/01/11 14:26:23 ERROR ovs.go:114: openvswitch cmd failed: &{/bin/ovs-vsctl [/bin/ovs-vsctl add-br test_bridge] []  <nil>  ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)
 [] <nil> 0xc820262420 exit status 1 <nil> true [0xc8204b6018 0xc8204b6030 0xc8204b6050] [0xc8204b6018 0xc8204b6030 0xc8204b6050] [0xc8204b6028 0xc8204b6048] [0x613e90 0x613e90] 0xc820144120} ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)

2016/01/11 14:26:23 ERROR kvm.go:469: get bridge: ovsAddBridge: exit status 1: ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)

2016/01/11 14:26:23 ERROR ovs.go:114: openvswitch cmd failed: &{/bin/ovs-vsctl [/bin/ovs-vsctl add-br mega_bridge] []  <nil>  ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)
 [] <nil> 0xc8200cd780 exit status 1 <nil> true [0xc8204ce0d0 0xc8204ce0e8 0xc8204ce100] [0xc8204ce0d0 0xc8204ce0e8 0xc8204ce100] [0xc8204ce0e0 0xc8204ce0f8] [0x613e90 0x613e90] 0xc820407260} ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)

2016/01/11 14:26:23 ERROR kvm.go:469: get bridge: ovsAddBridge: exit status 1: ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)

2016/01/11 14:26:23 WARN vm.go:615: unallocated mac address: 13:37:13:37:00:02
2016/01/11 14:26:23 ERROR ovs.go:114: openvswitch cmd failed: &{/bin/ovs-vsctl [/bin/ovs-vsctl add-br test_bridge] []  <nil>  ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)
 [] <nil> 0xc8205d09c0 exit status 1 <nil> true [0xc8204b6110 0xc8204b6128 0xc8204b6140] [0xc8204b6110 0xc8204b6128 0xc8204b6140] [0xc8204b6120 0xc8204b6138] [0x613e90 0x613e90] 0xc820145980} ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)

2016/01/11 14:26:23 ERROR kvm.go:469: get bridge: ovsAddBridge: exit status 1: ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)

2016/01/11 14:26:23 WARN vm.go:615: unallocated mac address: 13:37:13:37:00:03
2016/01/11 14:26:23 WARN vm.go:615: unallocated mac address: 13:37:13:37:00:04
2016/01/11 14:26:23 ERROR ovs.go:114: openvswitch cmd failed: &{/bin/ovs-vsctl [/bin/ovs-vsctl add-br test_bridge] []  <nil>  ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)
 [] <nil> 0xc82036f380 exit status 1 <nil> true [0xc8204ce1d8 0xc8204ce1f0 0xc8204ce208] [0xc8204ce1d8 0xc8204ce1f0 0xc8204ce208] [0xc8204ce1e8 0xc8204ce200] [0x613e90 0x613e90] 0xc8204f4c60} ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)

2016/01/11 14:26:23 ERROR kvm.go:469: get bridge: ovsAddBridge: exit status 1: ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)

2016/01/11 14:26:23 ERROR ovs.go:114: openvswitch cmd failed: &{/bin/ovs-vsctl [/bin/ovs-vsctl add-br test_bridge] []  <nil>  ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)
 [] <nil> 0xc8204503c0 exit status 1 <nil> true [0xc8204b61d8 0xc8204b61f0 0xc8204b6208] [0xc8204b61d8 0xc8204b61f0 0xc8204b6208] [0xc8204b61e8 0xc8204b6200] [0x613e90 0x613e90] 0xc8200a2de0} ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)

2016/01/11 14:26:23 ERROR kvm.go:124: ovsAddBridge: exit status 1: ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40d9bc]

goroutine 617 [running]:
main.(*Bridge).queueRemove(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/jcrusse/code/minimega/src/minimega/bridge.go:927 +0x4fc
main.(*Bridge).TapDestroy(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/jcrusse/code/minimega/src/minimega/bridge.go:244 +0x45
main.(*KvmVM).Flush(0xc820072340, 0x0, 0x0)
        /home/jcrusse/code/minimega/src/minimega/kvm.go:126 +0x1dc
main.VMs.flush(0xc82046c4e0)
        /home/jcrusse/code/minimega/src/minimega/vmlist.go:263 +0x277
main.cliVmFlush(0xc82009b4f0, 0x1)
        /home/jcrusse/code/minimega/src/minimega/vm_cli.go:1233 +0x78
main.wrapSimpleCLI.func1(0xc82009b4f0, 0xc8200a2d80)
        /home/jcrusse/code/minimega/src/minimega/misc.go:268 +0x29
minicli.ProcessCommand.func1(0xc82009b4f0, 0xc8200a2d80)
        /home/jcrusse/code/minimega/src/minicli/minicli.go:130 +0x3c
created by minicli.ProcessCommand
        /home/jcrusse/code/minimega/src/minicli/minicli.go:139 +0x117
```

**Comment by jcrussell** [comment]
@djfritz

**Comment by jcrussell** [comment]
Going to take a look at this.

**Comment by jcrussell** [comment]
That's odd, yesterday it would panic every time I ran `minitest` but now it seems fine. Closing the issue.
