### ISSUE TITLE
minimega: fix panic

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#540]
```
panic: close of nil channel

goroutine 35577 [running]:
panic(0xac0460, 0xc82a9be9c0)
        /opt/go/src/runtime/panic.go:464 +0x3e6
ipmac.(*IPMacLearner).DelMac(0xc82ab5c700, 0xc82010d860, 0x11)
        /minimega/src/ipmac/ipmac.go:71 +0xbf
main.(*ContainerVM).launch.func1(0xc822a9c9a0, 0xc822849180, 0xc823ce56c0, 0x17)
        /minimega/src/minimega/container.go:1009 +0xb20
created by main.(*ContainerVM).launch
        /minimega/src/minimega/container.go:1028 +0x2cf2
```

**Comment by jcrussell** [comment]
Think I have a fix for this... needs testing.
