### ISSUE TITLE
protonuke: smtp crashes

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#571]
```
unexpected fault address 0xc82246c020
fatal error: fault
[signal 0xb code=0x1 addr=0xc82246c020 pc=0x470288]

goroutine 68 [running]:
runtime.throw(0x8c28b0, 0x5)
        /opt/go/src/runtime/panic.go:530 +0x90 fp=0xc8201bbb88 sp=0xc8201bbb70
runtime.sigpanic()
        /opt/go/src/runtime/sigpanic_unix.go:27 +0x2ab fp=0xc8201bbbd8 sp=0xc8201bbb88
runtime.memmove(0xc82246c020, 0xc8201bbf40, 0x50)
        /opt/go/src/runtime/memmove_amd64.s:177 +0x2e8 fp=0xc8201bbbe0 sp=0xc8201bbbd8
runtime.typedmemmove(0x8684e0, 0xc82246c020, 0xc8201bbf40)
        /opt/go/src/runtime/mbarrier.go:190 +0x29 fp=0xc8201bbc10 sp=0xc8201bbbe0
main.smtpClient(0xc82018e900, 0x8c5e90, 0x4)
        /home/jcrusse/mipm_fy16/src/protonewk/smtp.go:103 +0x1024 fp=0xc8201bbf98 sp=0xc8201bbc10
runtime.goexit()
        /opt/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8201bbfa0 sp=0xc8201bbf98
created by main.main
        /home/jcrusse/mipm_fy16/src/protonewk/protonuke.go:144 +0xdb6
```

emails should not be a global...

**Comment by jcrussell** [comment]
Oops, this is protonewk specific.
