### ISSUE TITLE
Panic in CLI for vm migrate tab completion

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#635]
```
minimega:/tmp/minimega/minimega$ vm migrate panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x68e9fe]

goroutine 1 [running]:
panic(0xbb3160, 0xc82000e100)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
meshage.(*Node).checkUpdateNetwork(0x0)
        /home/ubuntu/minimega/src/meshage/node.go:584 +0x7e
meshage.(*Node).BroadcastRecipients(0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/minimega/src/meshage/message.go:178 +0x4a
main.globalVMs(0x8)
        /home/ubuntu/minimega/src/minimega/vmlist.go:651 +0x650
main.GlobalVMs(0x0)
        /home/ubuntu/minimega/src/minimega/vmlist.go:634 +0x5a
main.cliVMSuggest(0x0, 0x0, 0xffffffffffffffff, 0x0, 0x0, 0x0)
        /home/ubuntu/minimega/src/minimega/vm_cli.go:861 +0xc8
main.glob.func18(0xc8202d980c, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/minimega/src/minimega/vm_cli.go:351 +0x89
minicli.(*Handler).suggest(0x11c6f90, 0xc8203689f0, 0x0, 0x0, 0x0)
        /home/ubuntu/minimega/src/minicli/handler.go:145 +0x9b7
minicli.suggest(0xc8203689f0, 0x0, 0x0, 0x0)
        /home/ubuntu/minimega/src/minicli/minicli.go:242 +0xd9
minicli.Suggest(0xc8203dadd0, 0xb, 0x0, 0x0, 0x0)
        /home/ubuntu/minimega/src/minicli/minicli.go:262 +0x16f
goreadline.minicomplete(0x7f3fd8013e00, 0xb0000000b, 0xc820047808)
        /home/ubuntu/minimega/src/goreadline/goreadline.go:61 +0x80
goreadline._cgoexpwrap_22ac367ed61f_minicomplete(0x7f3fd8013e00, 0xb0000000b, 0x0)
        ??:0 +0x6a
goreadline._Cfunc_readline(0x7f3fd80008c0, 0x0)
        ??:0 +0x3e
goreadline.Readline(0xc820368960, 0x21, 0xc820047a01, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/minimega/src/goreadline/goreadline.go:98 +0xc6
miniclient.(*Conn).Attach(0xc820377e80)
        /home/ubuntu/minimega/src/miniclient/client.go:152 +0x4ec
main.main()
        /home/ubuntu/minimega/src/minimega/main.go:148 +0x1fee
```
I typed vm migrate and pressed tab and got that. I don't see anything in the logs, they were set to warn. Repeatable.

https://github.com/sandia-minimega/minimega/issues/600

**Comment by jcrussell** [comment]
This is via the `-attach` interface, right?

The problem is that the CLI doesn't have enough of the running state to perform the completion. Will add this as a note of one of the places to fix on #600.
