### ISSUE TITLE
minimega: deadlock with mac snooper

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#749]
Seeing this in the stack trace:

```
goroutine 74 [syscall, 607 minutes, locked to thread]:
vendor/github.com/google/gopacket/pcap._Cfunc_pcap_next_ex(0x7fee1801dc90, 0xc820451330, 0xc820451338, 0x0)
        ??:0 +0x41
vendor/github.com/google/gopacket/pcap.(*Handle).getNextBufPtrLocked(0xc820451300, 0xc8214f2d70, 0x0, 0x0)
        /data/repos/minimega/src/vendor/github.com/google/gopacket/pcap/pcap.go:339 +0x329
vendor/github.com/google/gopacket/pcap.(*Handle).ReadPacketData(0xc820451300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /data/repos/minimega/src/vendor/github.com/google/gopacket/pcap/pcap.go:290 +0xca
bridge.(*Bridge).snooper(0xc821221b00)
        /data/repos/minimega/src/bridge/ipmac.go:41 +0x3b9
created by bridge.Bridges.newBridge
        /data/repos/minimega/src/bridge/bridges.go:116 +0x845

goroutine 29813 [semacquire, 602 minutes]:
sync.runtime_Semacquire(0xc82045132c)
        /usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc820451328)
        /usr/local/go/src/sync/mutex.go:83 +0x1c4
vendor/github.com/google/gopacket/pcap.(*Handle).Close(0xc820451300)
        /data/repos/minimega/src/vendor/github.com/google/gopacket/pcap/pcap.go:387 +0x35
bridge.(*Bridge).destroy(0xc821221b00, 0x0, 0x0)
        /data/repos/minimega/src/bridge/bridge.go:88 +0x153
bridge.Bridges.Destroy(0x55fa58eafd10, 0xb, 0xc820060360, 0xc821145d40, 0x0, 0x0)
        /data/repos/minimega/src/bridge/bridges.go:246 +0xe7
main.bridgesDestroy(0x0, 0x0)
        /data/repos/minimega/src/minimega/bridge.go:50 +0x4f
main.teardown()
        /data/repos/minimega/src/minimega/main.go:268 +0x94
main.cliQuit(0xc826bfe840, 0xc8212dde00, 0x0, 0x0)
        /data/repos/minimega/src/minimega/misc_cli.go:121 +0x28a
main.wrapSimpleCLI.func1(0xc826bfe840, 0xc826bfe960)
        /data/repos/minimega/src/minimega/cli.go:89 +0x96
minicli.ProcessCommand.func1(0xc826bfe840, 0xc826bfe960)
        /data/repos/minimega/src/minicli/minicli.go:147 +0x52
created by minicli.ProcessCommand
        /data/repos/minimega/src/minicli/minicli.go:165 +0x119
```

I thought that I fixed this by setting the timeout to 1 second when creating the pcap handle with `pcap.OpenLive`... it was blocking for a lot more than 1 second.

**Comment by jcrussell** [comment]
We've determined that this is because of changes to libpcap in v1.8.1. We created an issue on the gopacket/pcap (https://github.com/google/gopacket/issues/253) but it doesn't look like there's a simple solution.

A simple workaround is to write garbage to the interface until `pcap.Handle.Close` returns.
