### ISSUE TITLE
minimega: vnc crashes on blank lines

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#773]
Thought this was fixed by #758 but apparently it's still an issue:

```
panic: runtime error: index out of range

goroutine 207 [running]:
panic(0xce72c0, 0xc4200100e0)
        /usr/lib/golang/src/runtime/panic.go:481 +0x3e6
main.(*vncKBPlayback).playFile(0xc4215b4500)
        minimega/src/minimega/vnc_playback.go:206 +0xd61
created by main.(*vncKBPlayback).Play
        minimega/src/minimega/vnc_playback.go:343 +0x29c
```

File:

```
$ cat test.vnc
503553298:KeyEvent,true,h
54053754:KeyEvent,false,h

```

This appeared in the logs:

```
2016/11/28 18:10:45 ERROR vnc_record.go:224: strconv.ParseInt: parsing "": invalid syntax
```

**Comment by cdshann** [comment]
This is caused because the getDuration() function does some initial preprocessing of the vnc file to determine the total run time. I am working on making the line parsing more robust.
