### ISSUE TITLE
genapi.py: doesn't work anymore

### ISSUE THREAD

**Issue by jasoncontrib** [sandia-minimega/minimega#783]
There seems to be something about the capture API that `genapi.py` is not handling properly: it continues to recurse into `buildCommand()`, but `subs` is already length 0 (see below).

Do we even want to fix this script? E.g. #328 

```
Traceback (most recent call last):
  File "./genapi.py", line 147, in <module>
    sys.stdout.write(render(cmds))
  File "./genapi.py", line 126, in render
    buildCommand(context['cmds'], cmd.split(), c)
  File "./genapi.py", line 100, in buildCommand
    buildCommand(context[cmdName]['subcommands'], subs[1:], cmd)
  File "./genapi.py", line 94, in buildCommand
    cmdName = subs[0]
IndexError: list index out of range
```
The parameters during the final call to `buildCommand()`:
```
### buildCommand(context, subs, cmd): 
# subs:
[]
# cmd:
{u'help_long': u'',
 u'help_short': u'capture experiment data for a VM',
 u'parsed_patterns': [[{u'text': u'capture', u'type': 2},
                       {u'options': [u'pcap'],
                        u'text': u'pcap,',
                        u'type': 16},
                       {u'text': u'vm', u'type': 2},
                       {u'key': u'name', u'text': u'name', u'type': 8},
                       {u'key': u'interface',
                        u'text': u'interface index',
                        u'type': 8},
                       {u'key': u'filename',
                        u'text': u'filename',
                        u'type': 8}],
                      [{u'text': u'capture', u'type': 2},
                       {u'options': [u'pcap'],
                        u'text': u'pcap,',
                        u'type': 16},
                       {u'options': [u'delete'],
                        u'text': u'delete,',
                        u'type': 16},
                       {u'text': u'vm', u'type': 2},
                       {u'key': u'name', u'text': u'name', u'type': 8}]],
 u'patterns': [u'capture <pcap,> vm <name> <interface index> <filename>',
               u'capture <pcap,> <delete,> vm <name>'],
 u'shared_prefix': u'capture'}
# context:
{}
```

**Comment by jcrussell** [comment]
It's not worth fixing, I started working on generating the bindings in Go -- I should finish it up and get a PR up. 

We should add a note that the bindings are broken to the 2.3 release notes.
